### ISSUE TITLE
Error in running given example

### ISSUE THREAD

**Issue by avinoamshye** [raychaudhurilab/goshifter#2]
Running the example as given with proxy files created with ProxyFinder, I got the following error:

Traceback (most recent call last):
  File "./goshifter.py", line 187, in <module>
    args['--proxies'])
  File "/specific/netapp5_2/elkon/avinoamshye/goshifter/functions.py", line 109, in enrichPermRandBoundryPeakShift_tabixLd
    snpPeakInfo, ldsnpPeakInfo = permRandBoundryPeakShift(snpInfoChr,peaksTree,ldInfo,expand,minShift,maxShift,nPerm)
  File "/specific/netapp5_2/elkon/avinoamshye/goshifter/functions.py", line 304, in permRandBoundryPeakShift
    peaksToSnp = peaks2region(bounds,peaksTree,expand)
  File "/specific/netapp5_2/elkon/avinoamshye/goshifter/functions.py", line 425, in peaks2region
    maxbp = bounds[chrom][snp]['maxbp'] + expand
TypeError: unsupported operand type(s) for +: 'dict' and 'float'

It appears only some of the boundary values are still enclosed in dictionaries of the form {'bp': ... }
I could't find the reason for this so I added an if statement to extract the floats, assuming these values are the wanted ones.
This seem to work without any more errors, but I'm not sure the values inside the occasional dictionaries are correct. I'd love to hear your thoughts on this.

**Comment by erolaPC** [comment]
Hello,
I am having the same problem with proxy files created by ProxyFinder. Could you help me to solve it?

**Comment by sckinta** [comment]
Hello, I still have the same problem after `pull` the most updated commit. Could you help?

```
Traceback (most recent call last):
  File "./goshifter.py", line 187, in <module>
    args['--proxies'])
  File "/mnt/isilon/sfgi/programs/goshifter/functions.py", line 107, in enrichPermRandBoundryPeakShift_tabixLd
    snpPeakInfo, ldsnpPeakInfo = permRandBoundryPeakShift(snpInfoChr,peaksTree,ldInfo,expand,minShift,maxShift,nPerm)
  File "/mnt/isilon/sfgi/programs/goshifter/functions.py", line 301, in permRandBoundryPeakShift
    peaksToSnp = peaks2region(bounds,peaksTree,expand)
  File "/mnt/isilon/sfgi/programs/goshifter/functions.py", line 426, in peaks2region
    minbp = bounds[chrom][snp]['minbp'] - expand
TypeError: unsupported operand type(s) for -: 'dict' and 'float'
```

**Comment by Arya-bioinformatics** [comment]
I have the same problems
