### ISSUE TITLE
versioning issues

### ISSUE THREAD

**Issue by bschilder** [raychaudhurilab/goshifter#7]
Created a conda env to try and avoid versioning issues:

``` cat goshifter.yml```
```yml
name: goshifter
channels:
  - defaults
  - anaconda
  - conda-forge
  - bioconda
dependencies:
  - python<=2.7.9
  - bx-python
  - tabix
```

However, when I run the GoShifter:
```
/sc/arion/work/schilb03/conda/envs/goshifter/bin/python goshifter.py --snpmap Data/GWAS/Nalls23andMe_2019/BST1/GoShifter/snpmap.txt --annotation Data/GWAS/Nalls23andMe_2019/BST1/annotations/astrocytes/astrocytes.bed.txt.gz --permute 100 --ld Data/GWAS/Nalls23andMe_2019/BST1/GoShifter/LD --out Data/GWAS/Nalls23andMe_2019/BST1/GoShifter/astrocytes
```

....I get the following error which seems to indicate I'm not using the right version of `bx-python`.
```
Traceback (most recent call last):
  File "/hpc/users/schilb03/.Rlib/echolocatoR/tools/goshifter/goshifter.py", line 73, in <module>
    import functions
  File "/hpc/users/schilb03/.Rlib/echolocatoR/tools/goshifter/functions.py", line 43, in <module>
    from chromtree import ChromTree
  File "/hpc/users/schilb03/.Rlib/echolocatoR/tools/goshifter/chromtree.py", line 31, in <module>
    from bx.intervals.intersection import IntervalTree
  File "/hpc/packages/minerva-centos7/py_packages/3.7/lib/python3.7/site-packages/bx/intervals/__init__.py", line 7, in <module>
    from bx.intervals.intersection import *  # noqa: F40
ImportError: No module named intersection
```
 
Could you provide some info on which versions of each package are needed to use GoShifter?

**Comment by HaniceSun** [comment]
```
dependencies:
  - python=2.7
  - bx-python=0.7.4
  - tabix
  - numpy
  ```
  works for me.

**Comment by bschilder** [comment]
Awesome, thanks @HaniceSun! This seemed to work very nicely.

I'm attaching the updated yaml file:
[goshifter.yml.txt](https://github.com/immunogenomics/goshifter/files/9315283/goshifter.yml.txt)

I've also added it as one of the environments that can be installed with `echoconda`:
https://github.com/RajLabMSSM/echoconda
